swagger: '2.0'
info:
  title: person API
  description: person API
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
securityDefinitions:
  demo-user:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: demo-user@cuddly-spork.iam.gserviceaccount.com
    x-google-jwks_uri: "https://www.googleapis.com/robot/v1/metadata/x509/demo-user@cuddly-spork.iam.gserviceaccount.com"
    x-google-audiences: audience
paths:
  /v1/person/{id}:
    get:
      summary: person API v1
      parameters:
      - in: path
        name: id
        required: true
        type: integer
        minimum: 1
        description: person ID
      operationId: v1
      x-google-backend:
        address: https://cuddly-spork.uc.r.appspot.com/person
        path_translation: CONSTANT_ADDRESS
      responses:
        '200':
          description: success
          schema:
            type: string
  /v2/person/{id}:
    get:
      summary: person API v2
      parameters:
      - in: path
        name: id
        required: true
        type: integer
        minimum: 1
        description: person ID
      operationId: v2
      x-google-backend:
        address: https://person-riwryxeq2a-uc.a.run.app/person
        path_translation: CONSTANT_ADDRESS
      responses:
        '200':
          description: success
          schema:
            type: string
  /v3/person/{id}:
    get:
      summary: person API v3
      parameters:
      - in: path
        name: id
        required: true
        type: integer
        minimum: 1
        description: person ID
      operationId: v3
      x-google-backend:
        address: https://person-function-riwryxeq2a-uc.a.run.app
        path_translation: CONSTANT_ADDRESS
      responses:
        '200':
          description: success
          schema:
            type: string
      security:
        - demo-user: []
